-- liquibase formatted sql

-- changeset butt:1781167631620-1 splitStatements:false
CREATE TABLE files (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, photo BYTEA, CONSTRAINT "filesPK" PRIMARY KEY (id));

-- changeset butt:1781167631620-2 splitStatements:false
ALTER TABLE photos DROP COLUMN photo;

