spring.application.name=demo
spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/auth

jwt.key=hardToGuessString