spring.application.name=demo
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/auth

logging.level.org.springframework.security=TRACE
logging.charset.console=UTF-8
logging.charset.file=UTF-8

jwt.key=hardToGuessVeryLooooooonoooooooooogString

minio.url=https://127.0.0.1:9000
minio.user=bank_user
minio.password=password1234
minio.bucket=bank